# Generated by Django 3.0.3 on 2020-02-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=31)),
                ('commment', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('post_key', models.IntegerField()),
            ],
        ),
    ]
