# Generated by Django 3.0.3 on 2020-03-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200214_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31)),
                ('following', models.CharField(max_length=31)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='username',
        ),
    ]
