# Generated by Django 3.0.3 on 2020-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200305_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31)),
                ('liked_time', models.DateTimeField(auto_now=True)),
                ('post_key', models.IntegerField()),
            ],
        ),
    ]
